# Generated by Django 5.1.5 on 2026-08-05 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.CreateModel(
            name='RestockSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_empty_date', models.DateField(blank=True, null=True)),
                ('suggested_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('avg_daily_usage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restock_suggestions',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ('-settled_at',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('L', 'L'), ('g', 'g'), ('kg', 'kg'), ('units', 'units'), ('rolls', 'rolls'), ('packs', 'packs')], default='units', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount originally purchased', max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_threshold', models.PositiveIntegerField(default=3, help_text='Days of headroom before a restock alert fires')),
                ('days_until_empty', models.FloatField(blank=True, null=True)),
                ('predicted_empty_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usage_logs',
                'ordering': ('-logged_at',),
            },
        ),
    ]
