# Generated by Django 5.1.5 on 2026-08-05 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0002_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='households.household'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='households.household'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='households.household'),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchased_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_purchased', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restocksuggestion',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restock_suggestion', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='used_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['household', 'debtor'], name='idx_balance_debtor'),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.UniqueConstraint(fields=('household', 'debtor', 'creditor'), name='unique_balance_pair'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['household', 'payer'], name='idx_settle_payer'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['household', 'is_active'], name='idx_stock_household'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['stock', 'logged_at'], name='idx_usage_stock_time'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['used_by', 'logged_at'], name='idx_usage_user_time'),
        ),
    ]
